<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-InventoryService-1e4f8e36-aee9-4d6c-99e2-5462c252b6b9</UserSecretsId>

		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SportsStore\SportsStore.csproj" />
	</ItemGroup>

</Project>