name: SportsStore CI

'on':
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./SportsSln.sln

      - name: Build solution
        run: dotnet build ./SportsSln.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./SportsSln.sln --configuration Release
